# colors for elements
# color_primary = "#546de5"
# color_primary_dark = "#303952"
# color_accent_dark = "#596275"
# color_success = "#32ff7e"
# color_danger = "#e15f41"
# color_warning = "#f5cd79"
# color_info = "#18dcff"
# color_white = "#ffffff"

color_primary = "#7d5fff"
color_primary_dark = "#3d3d3d"
color_accent_dark = "#4b4b4b"
color_success = "#32ff7e"
color_danger = "#ff4d4d"
color_warning = "#ffaf40"
color_info = "#18dcff"
color_white = "#ffffff"
